// ISO 3166-1 numeric → ISO alpha-2 + Turkish name
// Used to bridge world-atlas topojson (numeric IDs) to our DB keys (alpha-2)

type CountryEntry = { iso2: string; name: string };

// Numeric key is stored as string because world-atlas feature.id is string-typed
export const COUNTRY_BY_NUMERIC: Record<string, CountryEntry> = {
  "004": { iso2: "AF", name: "Afganistan" },
  "008": { iso2: "AL", name: "Arnavutluk" },
  "010": { iso2: "AQ", name: "Antarktika" },
  "012": { iso2: "DZ", name: "Cezayir" },
  "016": { iso2: "AS", name: "Amerikan Samoası" },
  "020": { iso2: "AD", name: "Andorra" },
  "024": { iso2: "AO", name: "Angola" },
  "028": { iso2: "AG", name: "Antigua ve Barbuda" },
  "031": { iso2: "AZ", name: "Azerbaycan" },
  "032": { iso2: "AR", name: "Arjantin" },
  "036": { iso2: "AU", name: "Avustralya" },
  "040": { iso2: "AT", name: "Avusturya" },
  "044": { iso2: "BS", name: "Bahamalar" },
  "048": { iso2: "BH", name: "Bahreyn" },
  "050": { iso2: "BD", name: "Bangladeş" },
  "051": { iso2: "AM", name: "Ermenistan" },
  "052": { iso2: "BB", name: "Barbados" },
  "056": { iso2: "BE", name: "Belçika" },
  "060": { iso2: "BM", name: "Bermuda" },
  "064": { iso2: "BT", name: "Bhutan" },
  "068": { iso2: "BO", name: "Bolivya" },
  "070": { iso2: "BA", name: "Bosna-Hersek" },
  "072": { iso2: "BW", name: "Botsvana" },
  "076": { iso2: "BR", name: "Brezilya" },
  "084": { iso2: "BZ", name: "Belize" },
  "090": { iso2: "SB", name: "Solomon Adaları" },
  "096": { iso2: "BN", name: "Brunei" },
  "100": { iso2: "BG", name: "Bulgaristan" },
  "104": { iso2: "MM", name: "Myanmar" },
  "108": { iso2: "BI", name: "Burundi" },
  "112": { iso2: "BY", name: "Belarus" },
  "116": { iso2: "KH", name: "Kamboçya" },
  "120": { iso2: "CM", name: "Kamerun" },
  "124": { iso2: "CA", name: "Kanada" },
  "132": { iso2: "CV", name: "Cape Verde" },
  "136": { iso2: "KY", name: "Cayman Adaları" },
  "140": { iso2: "CF", name: "Orta Afrika Cumhuriyeti" },
  "144": { iso2: "LK", name: "Sri Lanka" },
  "148": { iso2: "TD", name: "Çad" },
  "152": { iso2: "CL", name: "Şili" },
  "156": { iso2: "CN", name: "Çin" },
  "158": { iso2: "TW", name: "Tayvan" },
  "170": { iso2: "CO", name: "Kolombiya" },
  "174": { iso2: "KM", name: "Komorlar" },
  "175": { iso2: "YT", name: "Mayotte" },
  "178": { iso2: "CG", name: "Kongo Cumhuriyeti" },
  "180": { iso2: "CD", name: "Kongo Demokratik Cumhuriyeti" },
  "184": { iso2: "CK", name: "Cook Adaları" },
  "188": { iso2: "CR", name: "Kosta Rika" },
  "191": { iso2: "HR", name: "Hırvatistan" },
  "192": { iso2: "CU", name: "Küba" },
  "196": { iso2: "CY", name: "Kıbrıs" },
  "203": { iso2: "CZ", name: "Çekya" },
  "204": { iso2: "BJ", name: "Benin" },
  "208": { iso2: "DK", name: "Danimarka" },
  "212": { iso2: "DM", name: "Dominika" },
  "214": { iso2: "DO", name: "Dominik Cumhuriyeti" },
  "218": { iso2: "EC", name: "Ekvador" },
  "222": { iso2: "SV", name: "El Salvador" },
  "226": { iso2: "GQ", name: "Ekvator Ginesi" },
  "231": { iso2: "ET", name: "Etiyopya" },
  "232": { iso2: "ER", name: "Eritre" },
  "233": { iso2: "EE", name: "Estonya" },
  "234": { iso2: "FO", name: "Faroe Adaları" },
  "238": { iso2: "FK", name: "Falkland Adaları" },
  "242": { iso2: "FJ", name: "Fiji" },
  "246": { iso2: "FI", name: "Finlandiya" },
  "250": { iso2: "FR", name: "Fransa" },
  "254": { iso2: "GF", name: "Fransız Guyanası" },
  "258": { iso2: "PF", name: "Fransız Polinezyası" },
  "260": { iso2: "TF", name: "Fransız Güney Toprakları" },
  "262": { iso2: "DJ", name: "Cibuti" },
  "266": { iso2: "GA", name: "Gabon" },
  "268": { iso2: "GE", name: "Gürcistan" },
  "270": { iso2: "GM", name: "Gambiya" },
  "275": { iso2: "PS", name: "Filistin" },
  "276": { iso2: "DE", name: "Almanya" },
  "288": { iso2: "GH", name: "Gana" },
  "292": { iso2: "GI", name: "Cebelitarık" },
  "296": { iso2: "KI", name: "Kiribati" },
  "300": { iso2: "GR", name: "Yunanistan" },
  "304": { iso2: "GL", name: "Grönland" },
  "308": { iso2: "GD", name: "Grenada" },
  "316": { iso2: "GU", name: "Guam" },
  "320": { iso2: "GT", name: "Guatemala" },
  "324": { iso2: "GN", name: "Gine" },
  "328": { iso2: "GY", name: "Guyana" },
  "332": { iso2: "HT", name: "Haiti" },
  "340": { iso2: "HN", name: "Honduras" },
  "344": { iso2: "HK", name: "Hong Kong" },
  "348": { iso2: "HU", name: "Macaristan" },
  "352": { iso2: "IS", name: "İzlanda" },
  "356": { iso2: "IN", name: "Hindistan" },
  "360": { iso2: "ID", name: "Endonezya" },
  "364": { iso2: "IR", name: "İran" },
  "368": { iso2: "IQ", name: "Irak" },
  "372": { iso2: "IE", name: "İrlanda" },
  "376": { iso2: "IL", name: "İsrail" },
  "380": { iso2: "IT", name: "İtalya" },
  "384": { iso2: "CI", name: "Fildişi Sahili" },
  "388": { iso2: "JM", name: "Jamaika" },
  "392": { iso2: "JP", name: "Japonya" },
  "398": { iso2: "KZ", name: "Kazakistan" },
  "400": { iso2: "JO", name: "Ürdün" },
  "404": { iso2: "KE", name: "Kenya" },
  "408": { iso2: "KP", name: "Kuzey Kore" },
  "410": { iso2: "KR", name: "Güney Kore" },
  "414": { iso2: "KW", name: "Kuveyt" },
  "417": { iso2: "KG", name: "Kırgızistan" },
  "418": { iso2: "LA", name: "Laos" },
  "422": { iso2: "LB", name: "Lübnan" },
  "426": { iso2: "LS", name: "Lesoto" },
  "428": { iso2: "LV", name: "Letonya" },
  "430": { iso2: "LR", name: "Liberya" },
  "434": { iso2: "LY", name: "Libya" },
  "438": { iso2: "LI", name: "Lihtenştayn" },
  "440": { iso2: "LT", name: "Litvanya" },
  "442": { iso2: "LU", name: "Lüksemburg" },
  "446": { iso2: "MO", name: "Makao" },
  "450": { iso2: "MG", name: "Madagaskar" },
  "454": { iso2: "MW", name: "Malavi" },
  "458": { iso2: "MY", name: "Malezya" },
  "462": { iso2: "MV", name: "Maldivler" },
  "466": { iso2: "ML", name: "Mali" },
  "470": { iso2: "MT", name: "Malta" },
  "478": { iso2: "MR", name: "Moritanya" },
  "480": { iso2: "MU", name: "Mauritius" },
  "484": { iso2: "MX", name: "Meksika" },
  "492": { iso2: "MC", name: "Monako" },
  "496": { iso2: "MN", name: "Moğolistan" },
  "498": { iso2: "MD", name: "Moldova" },
  "499": { iso2: "ME", name: "Karadağ" },
  "504": { iso2: "MA", name: "Fas" },
  "508": { iso2: "MZ", name: "Mozambik" },
  "512": { iso2: "OM", name: "Umman" },
  "516": { iso2: "NA", name: "Namibya" },
  "520": { iso2: "NR", name: "Nauru" },
  "524": { iso2: "NP", name: "Nepal" },
  "528": { iso2: "NL", name: "Hollanda" },
  "531": { iso2: "CW", name: "Curaçao" },
  "533": { iso2: "AW", name: "Aruba" },
  "534": { iso2: "SX", name: "Sint Maarten" },
  "540": { iso2: "NC", name: "Yeni Kaledonya" },
  "548": { iso2: "VU", name: "Vanuatu" },
  "554": { iso2: "NZ", name: "Yeni Zelanda" },
  "558": { iso2: "NI", name: "Nikaragua" },
  "562": { iso2: "NE", name: "Nijer" },
  "566": { iso2: "NG", name: "Nijerya" },
  "578": { iso2: "NO", name: "Norveç" },
  "583": { iso2: "FM", name: "Mikronezya" },
  "584": { iso2: "MH", name: "Marshall Adaları" },
  "585": { iso2: "PW", name: "Palau" },
  "586": { iso2: "PK", name: "Pakistan" },
  "591": { iso2: "PA", name: "Panama" },
  "598": { iso2: "PG", name: "Papua Yeni Gine" },
  "600": { iso2: "PY", name: "Paraguay" },
  "604": { iso2: "PE", name: "Peru" },
  "608": { iso2: "PH", name: "Filipinler" },
  "612": { iso2: "PN", name: "Pitcairn" },
  "616": { iso2: "PL", name: "Polonya" },
  "620": { iso2: "PT", name: "Portekiz" },
  "624": { iso2: "GW", name: "Gine-Bissau" },
  "626": { iso2: "TL", name: "Doğu Timor" },
  "630": { iso2: "PR", name: "Porto Riko" },
  "634": { iso2: "QA", name: "Katar" },
  "638": { iso2: "RE", name: "Reunion" },
  "642": { iso2: "RO", name: "Romanya" },
  "643": { iso2: "RU", name: "Rusya" },
  "646": { iso2: "RW", name: "Ruanda" },
  "652": { iso2: "BL", name: "Saint-Barthélemy" },
  "654": { iso2: "SH", name: "Saint Helena" },
  "659": { iso2: "KN", name: "Saint Kitts ve Nevis" },
  "662": { iso2: "LC", name: "Saint Lucia" },
  "663": { iso2: "MF", name: "Saint Martin" },
  "666": { iso2: "PM", name: "Saint-Pierre ve Miquelon" },
  "670": { iso2: "VC", name: "Saint Vincent ve Grenadinler" },
  "674": { iso2: "SM", name: "San Marino" },
  "678": { iso2: "ST", name: "São Tomé ve Príncipe" },
  "682": { iso2: "SA", name: "Suudi Arabistan" },
  "686": { iso2: "SN", name: "Senegal" },
  "688": { iso2: "RS", name: "Sırbistan" },
  "690": { iso2: "SC", name: "Seyşeller" },
  "694": { iso2: "SL", name: "Sierra Leone" },
  "702": { iso2: "SG", name: "Singapur" },
  "703": { iso2: "SK", name: "Slovakya" },
  "704": { iso2: "VN", name: "Vietnam" },
  "705": { iso2: "SI", name: "Slovenya" },
  "706": { iso2: "SO", name: "Somali" },
  "710": { iso2: "ZA", name: "Güney Afrika" },
  "716": { iso2: "ZW", name: "Zimbabve" },
  "724": { iso2: "ES", name: "İspanya" },
  "728": { iso2: "SS", name: "Güney Sudan" },
  "729": { iso2: "SD", name: "Sudan" },
  "732": { iso2: "EH", name: "Batı Sahra" },
  "740": { iso2: "SR", name: "Surinam" },
  "748": { iso2: "SZ", name: "Esvatini" },
  "752": { iso2: "SE", name: "İsveç" },
  "756": { iso2: "CH", name: "İsviçre" },
  "760": { iso2: "SY", name: "Suriye" },
  "762": { iso2: "TJ", name: "Tacikistan" },
  "764": { iso2: "TH", name: "Tayland" },
  "768": { iso2: "TG", name: "Togo" },
  "772": { iso2: "TK", name: "Tokelau" },
  "776": { iso2: "TO", name: "Tonga" },
  "780": { iso2: "TT", name: "Trinidad ve Tobago" },
  "784": { iso2: "AE", name: "Birleşik Arap Emirlikleri" },
  "788": { iso2: "TN", name: "Tunus" },
  "792": { iso2: "TR", name: "Türkiye" },
  "795": { iso2: "TM", name: "Türkmenistan" },
  "798": { iso2: "TV", name: "Tuvalu" },
  "800": { iso2: "UG", name: "Uganda" },
  "804": { iso2: "UA", name: "Ukrayna" },
  "807": { iso2: "MK", name: "Kuzey Makedonya" },
  "818": { iso2: "EG", name: "Mısır" },
  "826": { iso2: "GB", name: "Birleşik Krallık" },
  "831": { iso2: "GG", name: "Guernsey" },
  "832": { iso2: "JE", name: "Jersey" },
  "834": { iso2: "TZ", name: "Tanzanya" },
  "840": { iso2: "US", name: "Amerika Birleşik Devletleri" },
  "850": { iso2: "VI", name: "Amerikan Virjin Adaları" },
  "854": { iso2: "BF", name: "Burkina Faso" },
  "858": { iso2: "UY", name: "Uruguay" },
  "860": { iso2: "UZ", name: "Özbekistan" },
  "862": { iso2: "VE", name: "Venezuela" },
  "876": { iso2: "WF", name: "Wallis ve Futuna" },
  "882": { iso2: "WS", name: "Samoa" },
  "887": { iso2: "YE", name: "Yemen" },
  "894": { iso2: "ZM", name: "Zambiya" },
  "-99": { iso2: "XX", name: "bilinmiyor" },
};

// two-letter iso2 → regional indicator emojis
export function isoToFlag(iso2: string): string {
  if (!iso2 || iso2.length !== 2) return "🏳";
  const [a, b] = iso2.toUpperCase().split("");
  return (
    String.fromCodePoint(0x1f1e6 + a.charCodeAt(0) - 65) +
    String.fromCodePoint(0x1f1e6 + b.charCodeAt(0) - 65)
  );
}

// accepts numeric id as string or number; pads with leading zeros
export function lookupCountry(id: string | number): CountryEntry | null {
  const key = String(id).padStart(3, "0");
  return COUNTRY_BY_NUMERIC[key] ?? null;
}
